POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RhIiwiaWQiOiI1ZjMyN2JkMDBjMmZiYTIwMzQ5MTZjM2YiLCJpYXQiOjE1OTczMTA3NjV9.KQVIRPlaqaCAXRv-eUgE2mADYCzPoEvx-wvEpJmL8CY

{
    "title": "Christmas",
    "author": "Santa",
    "url": "http://awesome.com",
    "likes": 1
}
